Vagrant.configure("2") do |config|

  config.vm.box = "talos-systems/talos" 
  
  # VM 1
  config.vm.define "talos-vm1" do |vm1|
    vm1.vm.hostname = "talos-vm1"
    vm1.vm.network "private_network", ip: "192.168.33.101"
    vm1.vm.provider "virtualbox" do |vb|
      vb.name = "talos-vm1"
      vb.memory = "2048" # Adjust memory as needed
      vb.cpus = 2        # Adjust CPUs as needed
    end
  end

  # VM 2
  config.vm.define "talos-vm2" do |vm2|
    vm2.vm.hostname = "talos-vm2"
    vm2.vm.network "private_network", ip: "192.168.33.102"
    vm2.vm.provider "virtualbox" do |vb|
      vb.name = "talos-vm2"
      vb.memory = "2048"
      vb.cpus = 2
    end
  end

  # VM 3
  config.vm.define "talos-vm3" do |vm3|
    vm3.vm.hostname = "talos-vm3"
    vm3.vm.network "private_network", ip: "192.168.33.103"
    vm3.vm.provider "virtualbox" do |vb|
      vb.name = "talos-vm3"
      vb.memory = "2048"
      vb.cpus = 2
    end
  end

end

